### ISSUE TITLE
Proposal: Section 2 - Data Descriptor

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#3]
In your proposal, briefly describe the dataset and the variables that you will visualize:

- Include how many rows and columns there are in the dataset (that you plan to use).
- There should be a clear link to how the dataset and the variables you describe will help you solve your target audience's problem.
- Indicate at least one new variable that you are planning to derive/engineer for your visualizations.
  - If there are no new variables to derive, indicate what additional information you would have liked to have in the dataset to better be able to answer your research questions (even if it is impossible for you to engineer it).
- If you are planning to visualize a lot of columns, provide a high level description of the variable types rather than listing every single column.
  - For example, indicate that the dataset contains a variety of categorical variables for demographics and provide a brief list rather than describing every single variable.
  - You may also want to consider visualizing a smaller set of variables given the short duration of this project.

**Comment by celestezhao** [comment]
## Section 2 - Data Description

The dataset to be used in our project is the Global Food Prices dataset available on the open platform The Humanitarian Data Exchange (HDX) (https://data.humdata.org/dataset/global-wfp-food-prices). This dataset originates from the World Food Programme Price Database and encompasses recorded prices for food items such as maize, rice, beans, fish, and sugar. The price data spans 98 countries and approximately 3,000 markets, and its historical range extends back to 1992 for certain countries, although many countries have started reporting from 2003 onwards. The dataset is updated weekly but primarily comprises monthly data entries, and the data is organized by country due to its extensive volume.

For our visualization, we will focus on the subset converning the Japanese market and covering the time from 2011 to 2020. This subset contains around 1,180 records of food prices. Each record within the dataset has 14 variables:
- Date of the record: `date`.
- Market information: name - `market`; city or province of the market - `admin1`, `admin2`; geographical coordinates - `latitude`, `longitude`.
- Food item information: type and name - `category`, `commodity`; item unit - `unit` (e.g. 5kg).
- Details on pricing: type and flag - `pricetype` (e.g., retail, wholesale), `priceflag` (typically actual); price in local currency and its equivalent in USD - `currency`, `price`, `usdprice` (converted at the current exchange rate).

In addition to these existing variables, we will derive several new metrics to enhance our analysis:
- Annual average price: converting monthly price data for each food item into annual metrics to facilitate year-over-year comparisons.
- Food price growth rate: calculating the rate of price growth for each food item on a monthly or yearly basis, both sequentially and year-over-year.
- (Optional) Ratio of food price to GNI (Gross National Income) per capita: dividing the price of a specific food item by the country's per capita income, allowing for international comparisons (data on GNI required).

“There should be a clear link to how the dataset and the variables you describe will help you solve your target audience's problem.” (TBU)

EDA (TBU)

**Comment by tonyshumlh** [comment]
@celestezhao FYI the amendment of Section 2

> For our initial visualization, we will concentrate on the Japanese market, encompassing data from 2011 to 2020. This dataset comprises approximately 1,180 records of food prices. Following a proof-of-concept review, we plan to expand our dataset to include visualization support for major populous countries.

**Comment by celestezhao** [comment]
> @celestezhao FYI the amendment of Section 2
> 
> > For our initial visualization, we will concentrate on the Japanese market, encompassing data from 2011 to 2020. This dataset comprises approximately 1,180 records of food prices. Following a proof-of-concept review, we plan to expand our dataset to include visualization support for major populous countries.

Thank you Tony

**Comment by celestezhao** [comment]
Refined based on today's discussion. Further refinement will go with the entire proposal. Close this issue for now.
