### ISSUE TITLE
(milestone 2) 5. Reflection

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#33]
In this section, your group should document on what you have implemented in your dashboard so far and explain what is not yet implemented. It is important that you include what you know is not working in your dashboard, so that your TAs can distinguish between features in development and bugs.

Reflect on what you think your dashboard does well what its limitations are, and what are good future improvements and additions. This section should not be more than 500 words and the reflection-milestone2.md document should live in your GitHub.com repo in the doc folder.

**Comment by celestezhao** [comment]
5. Reflection

rubric={reasoning:12,writing:3}

- In this section, your group should clearly document which parts of your proposal/sketch you have implemented in your dashboard so far and explain what is not yet implemented.
- For anything that you have done differently than in your proposal/sketch explain why (e.g. implementation difficulty, explanation for why the new approach is more effective, etc).
- It is important that you include what you are aware of is not working in your dashboard, so that your TAs can distinguish between features in development and bugs.
- You should also explain if you have intentionally deviated from any of the best practices that we learned in 531 regarding effective visualizations.
- Reflect on what you think your dashboard does well currently what its limitations are, and what are good potential future improvements and additions.
- This section should not be more than 500 words and be written to the file reports/m2-reflection.md in your GitHub repo.

**Comment by srfrew** [comment]
Reviewed and ready for merge
